# Generated by Django 4.2.7 on 2023-11-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(verbose_name="Название статьи")),
                ("link", models.CharField(verbose_name="Ссылка на статью")),
                ("date", models.DateTimeField(verbose_name="Дата публикации")),
                ("author", models.CharField(verbose_name="Никнейм автора")),
                (
                    "author_link",
                    models.CharField(verbose_name="Ссылка на автора"),
                ),
                ("text", models.TextField(verbose_name="Текст статьи")),
            ],
        ),
        migrations.CreateModel(
            name="Hub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        unique=True, verbose_name="Название хаба"
                    ),
                ),
                ("period", models.TimeField(verbose_name="Период обхода")),
            ],
        ),
    ]
